name: CI/CD - Push to Dev

on:
  push:
    branches:
      - dev

jobs:
  push-to-staging:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  
        token: ${{ secrets.PAT_TOKEN }}

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'

    - name: Push to Staging Branch
      run: |
        git fetch origin
        git checkout staging
        git merge dev
        git push origin staging