name: CI/CD Pipeline

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev, staging, main ]

jobs:
  pr-checks:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, node]
    steps:
      - uses: actions/checkout@v4
      
      - name: Build application
        run: |
          if [ "${{ matrix.language }}" = "python" ]; then
            pip install -r backend/requirements.txt
          else
            npm install --prefix frontend
            npm run build --prefix frontend
          fi
          
      - name: Run tests
        run: |
          if [ "${{ matrix.language }}" = "python" ]; then
            pytest backend/tests/test_unit.py
          else
            npm test --prefix frontend -- --testPathPattern=frontend/src/__tests__/unit_tests.js
          fi

  dev-to-staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, node]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Build application
        run: |
          if [ "${{ matrix.language }}" = "python" ]; then
            pip install -r backend/requirements.txt
          else
            npm install --prefix frontend
            npm run build --prefix frontend
          fi
          
      - name: Run tests
        run: |
          if [ "${{ matrix.language }}" = "python" ]; then
            pytest backend/tests/test_unit.py
          else
            npm test --prefix frontend -- --testPathPattern=frontend/src/__tests__/unit_tests.js
          fi
          
      - name: Push to staging
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin staging:staging
          git checkout staging
          git merge dev
          git push origin staging

  staging-to-prod:
    runs-on: ubuntu-latest
    needs: dev-to-staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Build application
        run: |
          # Add your build commands here
          echo "Building application..."
          
      - name: Run all tests
        run: |
          # Add your test commands here
          echo "Running all tests..."
          
      - name: Run tests
        run: |
          echo "Dummy test step for staging-to-prod..."
          
      - name: Push to main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin staging:staging
          git checkout main
          git merge staging
          git push origin main

  deploy-prod:
    runs-on: ubuntu-latest
    needs: staging-to-prod
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            your-dockerhub-username/your-app:latest
            your-dockerhub-username/your-app:${{ github.sha }}
            
      - name: Run tests
        run: |
          echo "Dummy test step for deploy-prod..."
          
      - name: Deploy to production
        run: |
          # Add your deployment commands here
          echo "Deploying to production..."